verify action IDs
prey/prey-node-client pull request #519
Opened 2021-10-14 13:48 UTC by patriciojofre

Major modifications on storage logic for commands, files, geofencing, triggers, etc.

2021-11-03 11:46 UTC, javo commented on lib/agent/actions/fileretrieval/index.js
> -      console.log(err);
devuelve ese, es necesario

2021-11-03 11:47 UTC, javo commented on lib/agent/actions/fileretrieval/storage.js
> -    console.log("ERR2", err)
aca reemplaza el console.log por un logger, hay que informar del error

2021-11-03 20:23 UTC, JohaoRosasRosillo commented on lib/agent/actions/fileretrieval/index.js
> -      console.log(err);
listo

2021-11-03 20:23 UTC, JohaoRosasRosillo commented on lib/agent/actions/fileretrieval/storage.js
> -    console.log("ERR2", err)
listo

2021-11-11 18:38 UTC, sebapintoag commented on lib/agent/actions.js
> +  logger.info('Running: ' + name + ' ' + id);
```suggestion
  logger.info(`Running: ${name} ${id}`);
```

2021-11-11 18:55 UTC, sebapintoag requested changes

2021-11-11 18:55 UTC, sebapintoag commented on lib/agent/actions.js
> +// revisar q hace esta funcion!
Es necesario que quede ese comentario?

2021-11-11 18:55 UTC, sebapintoag commented on lib/agent/actions.js
>      logger.info('Stopped: ' + name);
```suggestion
    logger.info(`Stopped: ${name}`);
```

2021-11-11 18:55 UTC, sebapintoag commented on lib/agent/actions.js
> +    // var err = new Error('Already running: ' + name);
```suggestion

```

2021-11-11 18:55 UTC, sebapintoag commented on lib/agent/actions.js
> +// agregar lo del opts para el response
Si se van a dejar comentarios así, mejor usar TO DO y en inglés idealmente.
Igual creo que es más fácil borrarlo.
```suggestion
// TODO: agregar lo del opts para el response
```

2021-11-11 18:55 UTC, sebapintoag commented on lib/agent/actions.js
> +
```suggestion

```

2021-11-11 18:55 UTC, sebapintoag commented on lib/agent/actions/fileretrieval/index.js
> +      logger.debug('Removing file_id from DB: ' + options.file_id);
```suggestion
      logger.debug(`Removing file_id from DB: ${options.file_id}`);
```

2021-11-11 18:55 UTC, sebapintoag commented on lib/agent/actions/fileretrieval/index.js
> +      logger.debug('Removing file_id from DB: ' + options.file_id);
```suggestion
      logger.debug(`Removing file_id from DB: ${options.file_id}`);
```

2021-11-11 18:55 UTC, sebapintoag commented on lib/agent/actions/geofencing/index.js
> +  // Se obtienen las zonas locales almacenadas
Es necesario tener comentarios en inglés y otros en español?

2021-11-11 18:55 UTC, sebapintoag commented on lib/agent/actions/lock/index.js
>        // console.log("Lock exited with code " + code);
```suggestion
      
```

2021-11-11 18:55 UTC, sebapintoag commented on lib/agent/actions/lock/index.js
>        // trying to kill me are you? ha-ha-ha.
what? xd

2021-11-11 18:55 UTC, sebapintoag commented on lib/agent/actions/lock/index.js
>        // emitter.emit('lock_murder_attempt');
```suggestion
      
```

2021-11-11 18:55 UTC, sebapintoag commented on lib/agent/actions/logretrieval/index.js
> +  //em.emit('end', id, err);
```suggestion
  
```

2021-11-11 18:55 UTC, sebapintoag commented on lib/agent/actions/triggers/index.js
> +        // return cb();
```suggestion
        
```

2021-11-11 18:55 UTC, sebapintoag commented on lib/agent/commands.js
> +    if (name == 'geofencing' || name == 'triggers' || name == 'fileretrieval') return cb && cb();
No se si acá será igual, pero al menos a mi en front con JS siempre me decían que era mejor usar `===` y no `==`

2021-11-11 18:55 UTC, sebapintoag commented on lib/agent/commands.js
> +      // }
```suggestion
 
```

2021-11-11 18:55 UTC, sebapintoag commented on lib/agent/providers/hardware/index.js
> +      console.log("ERROR!")  // modificar
Y algo así no sería más útil?
```suggestion
      console.log(e)
```

2021-11-11 18:55 UTC, sebapintoag commented on test/lib/agent/actions.js
> +      // })
```suggestion

```

2021-11-11 18:55 UTC, sebapintoag commented on test/lib/agent/actions/fixtures/triggers_responses.js
> +         // "date": "" + (new Date().getFullYear() +1) + "0725150006"     // "20200725150406" Always next year
```suggestion

```

2021-11-11 18:55 UTC, sebapintoag commented on test/lib/agent/actions/fixtures/triggers_responses.js
> +          // "date": "" + (new Date().getFullYear() +1) + "0725150007"
```suggestion

```

2021-11-11 18:55 UTC, sebapintoag commented on test/lib/agent/actions/triggers.js
> +      ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Hay varios de estos
```suggestion

```

2021-11-11 18:55 UTC, sebapintoag commented on test/lib/agent/actions/triggers.js
> +            // new_date = 1574261705000;
```suggestion

```

2021-11-11 18:55 UTC, sebapintoag commented on test/lib/agent/actions/triggers.js
> +          // })
```suggestion

```

2021-11-11 18:55 UTC, sebapintoag commented on test/lib/agent/updating_spec.js
> +          //       setTimeout(() => {
```suggestion

```

2021-11-11 19:11 UTC, JohaoRosasRosillo commented on lib/agent/actions/lock/index.js
>        // trying to kill me are you? ha-ha-ha.
xD

2021-11-11 20:54 UTC, jll90 approved these changes
Deje comentarios pero thumbs up!

2021-11-11 21:06 UTC, patriciojofre commented on lib/agent/actions/triggers/index.js
> +      } catch (e) {
¿mostrar la excepción?

2021-11-11 21:09 UTC, patriciojofre reviewed
coincido con @sebapintoag @jll90 en:

- manejo de try / catch: utilizar la variable `e` para enviar la excepción a algun lado y saber qu está ocurriendo un error (bugsnag/exceptions)
- comentarios en inglés o español
- snakeCase en lo posible (o para este PR, pero para el siguiente sería ideal)

2021-11-11 21:09 UTC, patriciojofre commented on lib/agent/commands.js
> +      logger.warn("Error parsing command options")
¿mostrar la excepción o enviarla a exceptions?

2021-11-12 12:13 UTC, javo approved these changes

2021-11-12 12:14 UTC, merged