fix ubuntu installation
prey/prey-node-client pull request #546
Opened 2022-01-25 18:30 UTC by SoraKenji

Fix for ubuntu installation. It fixes the problem on Firefox when opening a new web browser when an instance of firefox is already running.

2022-01-25 18:51 UTC, patriciojofre commented on lib/agent/plugins/control-panel/secure.js
> +      console.log(common.root_path);
🔪

2022-01-25 18:51 UTC, patriciojofre commented on lib/agent/plugins/control-panel/secure.js
> +      console.log(common.root_path);
🔪  console.logs...

2022-01-25 22:08 UTC, JohaoRosasRosillo approved these changes

2022-01-26 12:47 UTC, javo requested changes

2022-01-26 12:47 UTC, javo commented on lib/agent/plugins/control-panel/secure.js
> +        if(error){
puede quedar en una linea: if (error) return;

2022-01-26 12:47 UTC, javo commented on lib/agent/plugins/control-panel/secure.js
> +          if(err){
aca puedes dejarlo como if (err || stderr) return;
para que no quede más simplificado

2022-01-26 15:02 UTC, javo requested changes

2022-01-26 15:08 UTC, javo approved these changes

2022-01-26 18:00 UTC, merged